server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/tdxhhw66/springcloudconfig.git
          searchPaths: respo
#          username: your username
#          password: your password
