server:
  port: 8089

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/tdxhhw66/springcloudconfig.git/
          searchPaths: spring-config
#          username: your username
#          password: your password
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/